# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Canonical Ltd.
# Copyright 2024 Intel Corporation
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    uses: networkgcorefullcode/.github/.github/workflows/build.yml@main
    with:
      branch_name: ${{ github.ref }}

  docker-build:
    uses: networkgcorefullcode/.github/.github/workflows/docker-build.yml@main
    with:
      branch_name: ${{ github.ref }}

  static-analysis:
    uses: networkgcorefullcode/.github/.github/workflows/static-analysis.yml@main
    with:
      branch_name: ${{ github.ref }}

  lint:
    uses: networkgcorefullcode/.github/.github/workflows/lint.yml@main
    with:
      branch_name: ${{ github.ref }}

  hadolint:
    uses: networkgcorefullcode/.github/.github/workflows/hadolint.yml@main
    with:
      branch_name: ${{ github.ref }}

  license-check:
    uses: networkgcorefullcode/.github/.github/workflows/license-check.yml@main
    with:
      branch_name: ${{ github.ref }}

  fossa-scan:
    uses: networkgcorefullcode/.github/.github/workflows/fossa-scan.yml@main
    with:
      branch_name: ${{ github.ref }}

  unit-tests:
    uses: networkgcorefullcode/.github/.github/workflows/unit-test.yml@main
    with:
      branch_name: ${{ github.ref }}

  e2e-tests:
    if: github.event_name == 'pull_request'
    uses: networkgcorefullcode/.github/.github/workflows/e2e-test.yml@main
    with:
      branch_name: ${{ github.ref }}
